### ISSUE TITLE
GEQU with segment displacement

### ISSUE THREAD

**Issue by ksherlock** [byteworksinc/Linker#5]
Apple's linker (LinkIIgs for MPW and presumably their APW linker) handles gequ displacements as expected:

```
root	start
	end

seg1	start
	bra abc
	end

seg2	start
	nop
abc	gequ *
	rts
	end
```

ORCA Linker:
```
000045 000000 |             mx     %11
000045 000000 |             equ    *
000045 000000 |             bra    $0000   {-02}
00004c 000002 |             nop     
00004d 000003 |             rts 
```

LinkIIgs:
```
000037 000000 |             mx     %11
000037 000000 |             equ    *
000037 000000 |             bra    $0003   {+01}
00003e 000002 |             nop     
00003f 000003 |             rts  
```

I think the easiest way to handle it is to do the displacement adjustment in pass 1, before copying the expression into the symbol table, eg
```
diff --git a/exp.asm b/exp.asm
index 73e4a6b..9c93f8b 100644
--- a/exp.asm
+++ b/exp.asm
@@ -588,9 +588,23 @@ rf1	rts
 ;
 SegDisp	anop
 
+	using Common
+
 	lda	#1	copiedExpression = true
 	sta	copiedExpression
 	jsr	CheckStack	make sure there is room on the stack
+
+	clc		save the value + startpc
+	lda	startpc
+	ldy	#1
+	adc	[ep],Y
+	sta	[ep],Y
+	lda	startpc+2
+	iny
+	iny
+	adc	[ep],Y
+	sta	[ep],Y
+
 	add4	ep,#5	skip the op code and operand
 	add2	sp,#4	reserve space on the operand stack
 	rts
@@ -1403,16 +1417,15 @@ rf1	rts
 SegDisp	anop
 
 	jsr	CheckStack	make sure there is room on the stack
-	clc		save the value + startpc
-	lda	startpc
+
 	ldy	#1
-	adc	[ep],Y
+	lda	[ep],Y
 	sta	stack,X
-	lda	startpc+2
 	iny
 	iny
-	adc	[ep],Y
+	lda	[ep],Y
 	sta	stack+2,X
+
 	short M	value is relocatable
 	lda	#1
 	sta	stack+4,X
```

After:

```
000045 000000 |             mx     %11
000045 000000 |             equ    *
000045 000000 |             bra    $0003   {+01}
00004c 000002 |             nop     
00004d 000003 |             rts   
```

**Comment by sheumann** [comment]
It looks like you're using a version of ORCA/Linker prior to commit da13b94a4339b9. In those versions, expression with non-constant operands in EQU and GEQU records just weren't evaluated properly at all, and they would often be treated as having a value of 0.

After that commit, they are evaluated, and the output from ORCA/Linker should now be:

```
0000e3 000000 |             mx     %11
0000e3 000000 |             equ    *
0000e3 000000 |             bra    $0001   {-01}             80 ff       - ..
0000ea 000002 |             nop                              ea          - .
0000eb 000003 |             rts                              60          - `
```

It produces this output because the expression from the EQU or GEQU is evaluated in the context of the location where it is referenced, rather than the location where it is defined. In this case, the expression produced means "location at displacement +1 in the current segment", and that is evaluated in the context of seg1 (rather than seg2).

I know that result is not what would be expected based on the assembly syntax, and per your report it also does not match what LinkIIGS does. I don't think the documentation is very clear on this, but based on those precedents, it would probably be better to handle it the other way.

However, fully doing that requires more extensive changes than your proposed patch. It only addresses SegDisp ($87) operands, but similar handling should be applied to PCounter ($80) operands too, and they do not have the space to be updated in place like your patch does. Furthermore, there can be differences in what symbols are in scope, and therefore a symbol name might be resolved differently in the two places.

Addressing this all might require fairly involved changes, maybe more or less adding a new mini-pass. I'd welcome a patch, or I may do it myself at some point. However, the current behavior is at least consistent, so I'm reluctant to change just one part (e.g. the handling of SegDisp) without the rest.

**Comment by ksherlock** [comment]
Ah, you're right.  I rebuilt with https://github.com/byteworksinc/Linker/commit/da13b94a4339b94b359076fb55d60303d43fdff8 before testing but maybe it wasn't installed correctly.  The "simple" fix doesn't seem to work correctly with libraries, either.

I encountered the https://github.com/byteworksinc/Linker/commit/da13b94a4339b94b359076fb55d60303d43fdff8 issue [converting cc65/ca65 object files to OMF](https://github.com/ksherlock/cc65-to-omf), then encountered the segment displacement issue narrowing down that bug.  https://github.com/byteworksinc/Linker/commit/da13b94a4339b94b359076fb55d60303d43fdff8 fixes all the original issues.
